import { FetchedOrderType } from "../types";

export const fetchOrders = async (): Promise<FetchedOrderType[]> => {
  const orders: FetchedOrderType[] = [
    {
      id: "1",
      orderId: "#20345",
      amount: "₹100.00",
      status: "New",
      store: "Queenstown Public House",
      deliveryAddress: "6391 Elgin St. Celina, Delaware 10299",
      deliveryMode: "Home delivery",
      scheduledDate: "January 26",
      scheduledTime: "06:30 PM",
      paymentMethod: "Cash",
      createdDate: "2025-02-12",
    },
    {
      id: "2",
      orderId: "#20346",
      amount: "₹200.00",
      status: "Pending",
      store: "Plumed Horse",
      deliveryAddress: "8502 Preston Rd. Inglewood, Maine 98380",
      deliveryMode: "Home delivery",
      scheduledDate: "January 27",
      scheduledTime: "07:30 PM",
      paymentMethod: "UPI",
      createdDate: "2025-02-15",
    },
    {
      id: "3",
      orderId: "#20347",
      amount: "₹300.00",
      status: "New",
      store: "King Lee's",
      deliveryAddress: "3517 W. Gray St. Utica, Pennsylvania 57867",
      deliveryMode: "Home delivery",
      scheduledDate: "May 27",
      scheduledTime: "12:30 PM",
      paymentMethod: "Credit Card",
      createdDate: "2025-02-18",
    },
    {
      id: "4",
      orderId: "#20348",
      amount: "₹400.00",
      status: "New",
      store: "Marina Kitchen",
      deliveryAddress: "4140 Parker Rd. Allentown, New Mexico 31134",
      deliveryMode: "Home delivery",
      scheduledDate: "March 17",
      scheduledTime: "03:10 AM",
      paymentMethod: "Cash",
      createdDate: "2025-02-20",
    },
    {
      id: "5",
      orderId: "#20349",
      amount: "₹500.00",
      status: "New",
      store: "The Aviary",
      deliveryAddress: "4517 Washington Ave. Manchester, Kentucky 39495",
      deliveryMode: "Home delivery",
      scheduledDate: "April 17",
      scheduledTime: "03:10 AM",
      paymentMethod: "UPI",
      createdDate: "2025-02-22",
    },
    {
      id: "6",
      orderId: "#20350",
      amount: "₹600.00",
      status: "New",
      store: "Crab Hut",
      deliveryAddress: "2715 Ash Dr. San Jose, South Dakota 83475",
      deliveryMode: "Home delivery",
      scheduledDate: "April 17",
      scheduledTime: "03:10 AM",
      paymentMethod: "Credit Card",
      createdDate: "2025-02-24",
    },
    {
      id: "7",
      orderId: "#20351",
      amount: "₹700.00",
      status: "New",
      store: "Brass Tacks",
      deliveryAddress: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
      deliveryMode: "Home delivery",
      scheduledDate: "August 22",
      scheduledTime: "05:22 AM",
      paymentMethod: "Cash",
      createdDate: "2025-02-25",
    },
    {
      id: "8",
      orderId: "#20352",
      amount: "₹800.00",
      status: "Completed",
      store: "Bean Around the World Coffees",
      deliveryAddress: "2715 Ash Dr. San Jose, South Dakota 83475",
      deliveryMode: "Home delivery",
      scheduledDate: "August 22",
      scheduledTime: "05:22 AM",
      paymentMethod: "UPI",
      createdDate: "2025-02-26",
    },
    {
      id: "9",
      orderId: "#20353",
      amount: "₹900.00",
      status: "Cancelled",
      store: "Chewy Balls",
      deliveryAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
      deliveryMode: "Home delivery",
      scheduledDate: "August 22",
      scheduledTime: "05:22 AM",
      paymentMethod: "Credit Card",
      createdDate: "2025-02-27",
    },
    {
      id: "10",
      orderId: "#20354",
      amount: "₹1000.00",
      status: "Out for delivery",
      store: "Proxi",
      deliveryAddress: "2118 Thornridge Cir. Syracuse, Connecticut 35624",
      deliveryMode: "Home delivery",
      scheduledDate: "August 22",
      scheduledTime: "05:22 AM",
      paymentMethod: "Cash",
      createdDate: "2025-02-28",
    },
  ];
  try {
    const data = await new Promise((resolve) => {
      setTimeout(() => {
        resolve(orders);
      }, 1000); // Simulate a 1-second delay
    });

    return data as FetchedOrderType[];
  } catch (error) {
    throw error;
  }
};
